// Autogenerated by Nightwatch
// Refer to the online docs for more details: https://nightwatchjs.org/gettingstarted/configuration/
require('babel-core/register')
const chromedrive = require('chromedriver');

module.exports = {
  // An array of folders (excluding subfolders) where your tests are located;
  // if this is not specified, the test source must be passed as the second argument to the test runner.
  src_folders: ['tests'],

  page_objects_path:'./pages',
  globals_path: './hooks/globals.js',

  // See https://nightwatchjs.org/guide/working-with-page-objects/

  webdriver: {
    start_process: true,
    server_path: chromedrive.path,
    port: 9515
  },

  test_workers: {
    enabled: true,
    workers: 3,
  },

  test_settings: {
    default: {
      globals: {
        waitForConditionTimeout: 15000
      },
      desiredCapabilities: {
        browserName : 'chrome'
      },
    }
  }
}